### ISSUE TITLE
Kanban Board Submission

### ISSUE THREAD

**Issue by aamir-asaram** [Zohra-Neda/DriveShare-Back-End#14]
**Hi code reviewer!**
We are a group of 4:
- @aamir-asaram 
- @BenM4k 
- @manzitresor 
- @Zohra-Neda 

- This is the link to our [Kanban Board](https://github.com/Zohra-Neda/Final-Capstone-Back-End/projects/1)

- Below is a screenshot of our initial Kanban Board:

![kanban](https://github.com/Zohra-Neda/Final-Capstone-Back-End/assets/76215321/bd79c58f-351d-4d94-a4b6-f5809559c909)

**Comment by Meltrust** [comment]
Hi @aamir-asaram,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
